"""empty message

Revision ID: 688792d038ee
Revises: b51bc977fdae
Create Date: 2018-07-05 11:27:16.541939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688792d038ee'
down_revision = 'b51bc977fdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peminjam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_anggota', sa.Integer(), nullable=False),
    sa.Column('kd_buku', sa.String(length=10), nullable=False),
    sa.Column('tgl_pinjam', sa.DATE(), nullable=False),
    sa.Column('tgl_kembali', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peminjam')
    # ### end Alembic commands ###
