"""empty message

Revision ID: be1d2a91384e
Revises: 
Create Date: 2018-07-05 11:12:25.686988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1d2a91384e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kd_buku', sa.String(length=10), nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('pengarang', sa.String(length=30), nullable=False),
    sa.Column('penerbit', sa.String(length=20), nullable=False),
    sa.Column('tahun_terbit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buku')
    # ### end Alembic commands ###
